name: tictactoe
description: "A clean architecture Tic Tac Toe game."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  confetti: ^0.8.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.3
  intl: any
  package_info_plus: ^10.1.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true
